rvm: 1.9.3
env:
  - PUPPET_VERSION=3.7.3
script:
  - bundle exec rake lint
  - bundle exec rake validate
  - bundle exec rake spec
before_deploy:
  - bundle exec rake clean
  - bundle exec rake set_travis_version
deploy:
  skip_cleanup: true
  provider: puppetforge
  user:
    secure: "n2wY/jWDj8Wf+BQuCNY38nNn0bxOwUsFlGL+7+SWP6lDXdqLfiDTbMZLD5p3XFwWMw0JD6MeqAVCmJrtUFjD5/67hoGHQZVm6/iw/db0R4zPj+PUeZscwIm0pGhCsEwLScDtPLtq80s7La5EXiaPnwTKYCgQL34iRljWIWxUJaA="
  password:
    secure: "dI9LjSnxjot3eQ4T2ntrfKJc2XQbqd9IoHZ0h8uK2kP8zqHHAKkfb7x3/CgzGIXRlF06i1W9NNhN2hhWWJKDl+JmLYi6KJIAwX0WE04FSen0/L4ySut+T0800uXecyVR43Zg0cdtM5i35/QWtcSIXybtHCqw2wQToz/a7JRyWYU="
